#

import pandas as pd

In [1]:
import pandas as pd

In [2]:
DATA1=pd.DataFrame.from_dict(dict([("A",[1,2,3,4,5]),("B",[6,7,8,9,10])]))

In [6]:
DATA1

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [3]:
DATA1-DATA1.iloc[0]

   A  B
0  0  0
1  1  1
2  2  2
3  3  3
4  4  4

In [5]:
print(DATA1  * 5 + 2)

    A   B
0   7  32
1  12  37
2  17  42
3  22  47
4  27  52

In [7]:
DATA1 **2

    A    B
0   1   36
1   4   49
2   9   64
3  16   81
4  25  100

In [13]:
DF1 = pd.DataFrame({"A":[1,0,1],"B":[0,1,1]},dtype=bool)
DF2 = pd.DataFrame({"A":[1,0,0],"B":[0,1,0]},dtype=bool)

In [14]:
DF1

       A      B
0   True  False
1  False   True
2   True   True

In [15]:
DF1 & DF2 #AND

       A      B
0   True  False
1  False   True
2  False  False

In [16]:
DF1 | DF2 # OR

       A      B
0   True  False
1  False   True
2   True   True

In [17]:
DF1 ^ DF2    #XOR

       A      B
0  False  False
1  False  False
2   True   True

In [18]:
-DF1      #OPPOSITE

       A      B
0  False   True
1   True  False
2  False  False

In [23]:
DF1.gt(DF2)     # > greater than

       A      B
0  False  False
1  False  False
2   True   True

In [24]:
DF1.ne(DF2)    # not equal to

       A      B
0  False  False
1  False  False
2   True   True

In [26]:
import numpy as np

In [29]:
d=pd.DataFrame({"A":[1.0,np.nan,2.0,5.0,np.nan],"B":[np.nan,2.0,3.0,np.nan,6.0]})  # not a number =nan

In [30]:
d1=pd.DataFrame({"A":[5.0,2.0,4.0,np.nan,3.0,7.0],"B":[np.nan,np.nan,3.0,4.0,6.0,8.0]})

In [31]:
d

     A    B
0  1.0  NaN
1  NaN  2.0
2  2.0  3.0
3  5.0  NaN
4  NaN  6.0

In [32]:
d1

     A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [35]:
d.combine_first(d1)   # fille where both side NaN

     A    B
0  1.0  NaN
1  2.0  2.0
2  2.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

In [43]:
d3=pd.DataFrame({"A":[np.nan,3,7],"B":[np.nan,6,np.nan]},dtype='Int64')

In [45]:
d4=pd.DataFrame({"A":[1,np.nan,3],"B":[8,6,np.nan]},dtype='Int64')

In [46]:
d3

      A     B
0  <NA>  <NA>
1     3     6
2     7  <NA>

In [47]:
d4

      A     B
0     1     8
1  <NA>     6
2     3  <NA>

In [49]:
series= pd.Series(np.random.randn(500))       # give unique value amoong  500 range 
series[20:500]=np.nan
series[10:20] = 5
series.nunique()

11

In [52]:
series[30]

nan

In [55]:
frame=pd.DataFrame(np.random.randn(1000,5),columns=["a","b","c","d","e"])
frame[::2]=np.nan
frame

            a         b         c         d         e
0         NaN       NaN       NaN       NaN       NaN
1   -0.068441  1.072296 -0.455061 -1.227474  1.382682
2         NaN       NaN       NaN       NaN       NaN
3   -0.252851  0.149893  1.424448  1.511812  0.757611
4         NaN       NaN       NaN       NaN       NaN
..        ...       ...       ...       ...       ...
995 -0.711805 -0.353852 -0.827056 -0.687805  0.844614
996       NaN       NaN       NaN       NaN       NaN
997 -0.277100  0.721507 -0.752861  0.418818 -0.390728
998       NaN       NaN       NaN       NaN       NaN
999  0.515863  0.675252  1.778939 -0.133802  0.649508

[1000 rows x 5 columns]

In [58]:
frame=pd.DataFrame({"a":["yes","yes","no","no"],"b":range(4)})

In [59]:
print(frame)
frame.describe()

     a  b
0  yes  0
1  yes  1
2   no  2
3   no  3

              b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [61]:
data=np.random.randint(0,100,size=25)

In [62]:
data

array([42, 47, 73, 42, 60, 62,  5, 61, 73, 93, 95,  0, 72, 22, 46, 48, 24,
       61,  8, 41, 11, 15, 82, 84, 51])